apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: "postgresql-data"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
         - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: dane
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts: 
          - name: dane
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: dane
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi